
#pragma once
#ifndef ___ERROR_H
#define ___ERROR_H

typedef enum {
	ERROR_NONE								= 0,
	ERROR_FAILED							= 1,

	ERROR_BLOCK_TRANSACTION_NONE			= 0,
	ERROR_BLOCK_TRANSACTION_FAILED			= 0xa,
	ERROR_BLOCK_TRANSACTION_SLOT_IN_USE		= 0xb,
	ERROR_BLOCK_TRANSACTION_SIGNATURE_INVALID = 0xc,
	ERROR_BLOCK_TRANSACTION_INSUFFICIENT_FUNDS = 0xd,
	ERROR_BLOCK_TRANSACTION_DUPLICATE = 0xe,

	ERROR_WRITE_TO_FILE						= 0x10,
	ERROR_OPEN_FILE							= 0x11,

	ERROR_NETWORK_NONE						= 0x00,
	ERROR_NETWORK_FAILED					= 0x20

	
} error_t;

#endif
